name: build

on:
  push:
    tags:
      - '*'

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    
    - name: build with make
      run: make
  
    - name: create release assets
      id: create_release_asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./target/shoggoth-release-v0.4.5-Linux-x86_64.zip
        asset_name: release.zip
            asset_content_type: application/zip
