name: release

on:
  release:
    types: [published]

jobs:
  release-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    
    - name: build with make
      run: make

    - name: Read Version from version.txt
      id: read_version
      run: echo "::set-output name=version::$(cat version.txt)"
  
    - name: create release assets
      id: create_release_asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./target/shoggoth-release-v${{ steps.read_version.outputs.version }}-Linux-x86_64.zip
        asset_name: shoggoth-v${{ steps.read_version.outputs.version }}-Linux-x86_64.zip
        asset_content_type: application/zip


  release-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    
    - name: build with make
      run: make
  
    - name: create release assets
      id: create_release_asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./target/shoggoth-release-v${{ steps.read_version.outputs.version }}-Darwin-x86_64.zip
        asset_name: shoggoth-v${{ steps.read_version.outputs.version }}-Linux-x86_64.zip
        asset_content_type: application/zip
