name: tests (Camel)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: build with make
      run: make dev
    - name: run tests
      run: make test
    - name: test libs
      run: make test-libs
  
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: build with make
      run: make dev
    - name: run tests
      run: make test
    - name: test libs
      run: make test-libs
  
